### ISSUE TITLE
About the trivariate copula model

### ISSUE THREAD

**Issue by DDDDgood** [mkhoirun-najiboi/mycopula#1]
It's nice for you to share the code, thank you very much. I can use and repeat the bivariate copula follow your steps, but i could not find the trivariate copula model in the package. Maybe I was not careful enough to find this content, or you have other content that has not been uploaded. I hope to get your help, which is very helpful to me!

**Comment by mkhoirun-najiboi** [comment]
I have updated the content, please try again for the 3-copula case. You can let me know if there are still problems.
